---
title: ""
---
<style>
.container {
  position: relative;
  width: 100%;
  overflow: hidden;
  padding-top: 0%; /* 16:9 Aspect Ratio */
}

.responsive-iframe {
  position: realtive;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
  border: none;
}
</style>




<div class="col-sm-8 col-sm-offset-2">



<div class="container"> 
  <iframe class="responsive-iframe" src="file_html/presentaciones.html" name="iframe_a" scrolling="no" style=" height: 100px;"></iframe>
</div>
<p><a href="file_html/presentaciones.html" target="iframe_a">mera</a></p>



</div>

<!-- Aca inicia el footer -->
</div>
<div> 

<footer id="footer">
<div class="container">
<div class="row">
<div class="col-md-3 widget">
<h3 class="widget-title">Contact</h3>
<div class="widget-body">
<p>+57<br><a href="mailto:duvanieves@misena.edu.co">e-mail</a><br>Pilarica Robledo, Medellín, Colombia</p>
</div>
</div>
<div class="col-md-3 widget">
<h3 class="widget-title">Follow me</h3>
<div class="widget-body">
<p class="follow-me-icons">
<a href="https://www.facebook.com/Duvancho321" target="_blank"><i class="fa fa-facebook-square fa-2"></i></a>
<a href="https://twitter.com/DuvanNievesRui1" target="_blank"><i class="fa fa-twitter-square fa-2"></i></a>
<a href="https://www.instagram.com/el.individuo" target="_blank"><i class="fa fa-instagram fa-2"></i></a>
<a href="https://github.com/Duvancho321" target="_blank"><i class="fa fa-github fa-2"></i></a>
<a href="https://www.linkedin.com/in/duvancho321" target="_blank"><i class="fa fa-linkedin fa-2"></i></a>
</p>
</div>
</div>
<div class="col-md-3 widget">
<h3 class="widget-title">Text widget</h3>
<div class="widget-body">
<p align="justify">Necesitamos tomar la información, donde esté guardada, hacer nuestras copias y compartirlas con el mundo. Necesitamos tomar las cosas que no tengan copyright y añadirlas al archivo. Necesitamos pelear por el Guerilla Open Access. Suficientes de nosotros, alrededor del mundo, no solo mandaremos un mensaje fuerte que se opone a la privatización del conocimiento - lo haremos una cosa del pasado. ¿Te unirás a nosotros?</p>
</div>
</div>
<div class="col-md-3 widget">
<h3 class="widget-title">Contact</h3>
<div class="widget-body">
<p>+57<br><a href="mailto:duvanieves@misena.edu.co">e-mail</a><br>Pilarica Robledo, Medellín, Colombia</p>
</div>
</div>
</div> 
</div>
</footer>

<footer id="underfooter">
<div class="container">
<div class="row">
<div class="col-md-6 widget">
<div class="widget-body">
<p>Pilarica Robledo, Medellín, Colombia</p>
</div>
</div>
<div class="col-md-6 widget">
<div class="widget-body">
<p class="text-right">Copyleft© 2019, Duvan Nieves <br>Design: <a href="http://www.gettemplate.com" rel="designer">Initio by GetTemplate</a></p>
</div>
</div>
</div> 
</div>
</footer>